on: workflow_dispatch

jobs:
  cairo:
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-15, macos-15-intel ]
        
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - run: brew install gettext
    - run: pkg-config --libs --static cairo
    - run: cc -o test-cairo.o -c test-cairo.c
    - run: cc -o test-cairo test-cairo.o $(pkg-config --libs --static cairo)
    
